version: 2

sources:
  - name: staging
    database: de-zoomcamp-2024-411615
     # For postgres:
      #database: production
    schema: trips_data_all

      # loaded_at_field: record_loaded_at
    tables:
      - name: fhv_tripdata
         # freshness:
           # error_after: {count: 6, period: hour}
models:
    - name: stg_fhv_tripdata
      description: > 
        Trips made by New York City's. In a FHV (For Hire Veicule).
      columns:
          - name: dispatching_base_num 
            description: > 
                The TLC Base License Number of the base that dispatched the trip
          - name: pickup_datetime 
            description: > 
                The date and time of the trip pick-up
          - name: dropoff_datetime 
            description: > 
                The date and time of the trip dropoff
          - name: pickup_locationid
            description: TLC Taxi Zone in which the trip began.
          - name: dropoff_locationid 
            description: TLC Taxi Zone in which the trip ended.           
          - name: store_and_fwd_flag 
            description: > 
              Indicates if the trip was a part of a shared ride chain offered by a
              High Volume FHV company (e.g. Uber Pool, Lyft Line). For shared
              trips, the value is 1. For non-shared rides, this field is null              