
version: 2

sources:
    - name: staging
      #For bigquery:
      database: de-zoomcamp-2024-411615
      schema: trip_data_all

      # loaded_at_field: record_loaded_at
      tables:
        - name: green_tripdata
        - name: yellow_tripdata
         # freshness:
           # error_after: {count: 6, period: hour}